"""Write js/art-data.js (atlas frames + sheet layouts) from the build outputs."""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
A = os.path.join(ROOT, 'assets', 'art')
world = json.load(open(os.path.join(A, 'world.json')))
chars = json.load(open(os.path.join(A, 'chars', 'layout.json')))
data = {'world': dict(world, src='assets/art/world.png'), 'chars': {}}
for k, v in chars.items():
    data['chars'][k] = dict(v, src=f'assets/art/chars/{k}.png')
tdir = os.path.join(A, 'terrain')
if os.path.isdir(tdir):
    import terrain
    mats = {n: f'assets/art/terrain/{n}.jpg' for n in sorted(terrain.MATERIALS) if os.path.exists(os.path.join(tdir, n + '.jpg'))}
    data['terrain'] = {'d': terrain.D, 'period': terrain.PERIOD, 'materials': mats, 'caustics': 'assets/art/terrain/caustics.png'}
js = ('/* Generated by tools/art/build_manifest.py — do not edit by hand.\n'
      '   Atlas frames: name -> [x, y, w, h, anchorX, anchorY] in source px (2x logical). */\n'
      'window.SOTH_ART = ' + json.dumps(data, separators=(',', ':')) + ';\n')
open(os.path.join(ROOT, 'js', 'art-data.js'), 'w').write(js)
print('js/art-data.js', len(js), 'bytes')
